Repository ROBOTIS-GIT/ai_worker_website, pull requests merged in 2025-07, with the labels that each got.

#10 Modified typo
  docs/operation.md
  docs/setup.md
Labels: documentation

#17 Fixed incorrect OMX description on home page
  docs/index.md
Labels: bug, documentation

#20 modified omy models
  docs/public/overview/omy_models.png
Labels: documentation

#22 Fixed Bug and Updated Release Notes
  docs/.vitepress/config.mts
  docs/ai_worker/release_notes_ai_worker.md
  docs/omy/release_notes_omy.md
Labels: documentation

#23 Feature danger
  docs/ai_worker/operation_ai_worker.md
  docs/ai_worker/setup_guide_ai_worker.md
Labels: documentation

#25 added ai_worker gazebo images.
  docs/.vitepress/config.mts
  docs/ai_worker/gazebo_ai_worker.md
  docs/public/simulation/ai_worker/ffw_bg2_gazebo.png
  docs/public/simulation/ai_worker/ffw_sg2_gazebo.png
Labels: enhancement
